version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: linkary-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: linkary
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - linkary-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  linkary-network:
    driver: bridge
